version: '3.2'

services:

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      ELASTIC_PASSWORD: "elastic"
      discovery.type: single-node
      xpack.security.enabled: "true"
    ports:
      - "9207:9200"
      - "9300:9300"
    healthcheck:
      test: "wget -q -O - http://elastic:elastic@localhost:9200/_cat/health"
      interval: 1s
      timeout: 30s
      retries: 300
    networks:
      - elk

networks:
  elk:
