version: '3.2'

services:

  elasticsearch:
    image: elasticsearch:7.7.0
    container_name: elasticsearch
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    environment:
      ELASTIC_PASSWORD: "elastic"
      discovery.type: single-node
    ports:
      - "9201:9200"
    networks:
      - elk

networks:
  elk:
